[package]
name = "team-pastel-sky-piratejam" # TODO: Update name when game name is decided
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
console_error_panic_hook = "0.1.7"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
