name: Deploy

on: 
  push:
    branches:
      - release
jobs:
  deploy:
    name: Upload to Itch
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ubuntu-cargo-build-${{ hashFiles('**/Cargo.toml') }}
      - name: Install necessary rust toolchain components and cargo tools
        run: ./scripts/dev_setup.sh
      - name: build
        run: 'cargo build --release --target wasm32-unknown-unknown'
      - name: run `wasm-bindgen`
        run: 'wasm-bindgen --no-typescript --target web --out-dir ./web/ --out-name "phantasmeow-" ./target/wasm32-unknown-unknown/release/phantasmeow.wasm'
            
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.butlerApiKey}}
          gameData: ./web/
          itchUsername: pol4r1s
          itchGameId: phantasmeow
          buildChannel: "HTML5"

